'''
int(x)将x转化成整数类型
float（x）将x转换成浮点数类型
str（x）将x转换成字符串
chr（x）将整数x转换成一个字符
ord（x）将一个字符x转化成其对应的整数值
hex（x）将整数x转换成一个十六进制的字符串
oct（x）将整数x转换成一个八进制的字符串
bin（x）将整数x转换成一个二进制的字符串
'''
a=10.2
print(type(a))
a=int(a)
print(type(a))
a=float(a)
print(type(a))
b=10
print(type(b))
b=str(b)
print(type(b))
c=100
print(type(c))
c=chr(c)
print(type(c))
c=ord(c)
print(type(c))
print('-'*100)
x=10086
print(hex(x))
print(oct(x))
print(bin(x))
m=10
n=3
q=m/n
print(q)
print(int(3.14))
print(float(3))
print(int('100')+int('200'))