# ZeroDivisionError 当除数为0时，引发的异常
# IndexError  索引超出范围引发的异常
# KeyError   字典取值时key不存在的异常
# NameError   使用一个没有声明的变量时引发的异常
# SyntaxError Python中的语法错误
# ValueError  传入的值错误
# AttributeError 属性或方法不存在的异常
# TypeError  类型不合适引发的异常
# IndentationError 不正确的缩进引发的异常